name: Build Personalizado do RustDesk para Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configurar cache do Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Instalar dependências do vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        # Esta linha instrui o vcpkg a encontrar os arquivos vcpkg.json
        # no repositório e instalar as dependências listadas (como 'opus').
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Instalar Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Compilar o RustDesk
      env:
        RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
        RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
      run: cargo build --release --verbose

    - name: Fazer upload do executável como artefato
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-windows-personalizado
        path: target/release/rustdesk.exe
